dist: xenial
language: php
php: 7.3
cache:
  directories:
    - "$HOME/.composer/cache/files"

branches:
  only:
    - master

jobs:
  include:
    -
      stage: test
      install: composer install --no-interaction --no-progress
      script: php $TRAVIS_BUILD_DIR/vendor/bin/grumphp run
    -
      stage: release
      language: node_js
      node_js: 'lts/*'
      before_install:
        - git fetch origin --tags
      install:
        - npm install semantic-release-conventional-commits --no-save
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          branch: master
